import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
    en:{
        PleaseSignIn: "Please Sign In",
        username: "Username",
        password: "Password",
        dashboard: "Dashboard",
        search: "Search",
        StartSearch: "Start search",
        CreateSearchQueue: "Create search queue",
        bins: "Bins",
        ActiveBinData: "Active bin data",
        SignIn: "Sign In",
        Form: "Form",
        File: "File",
        SearchFormList: "Search Form List",
        SearchForm: "Search Form",
        Remove: "Remove",
        RemoveForm: "Remove form",
        AddNewForm: "Add new form",
        LoadFormsValues: "Load forms values",
        AddAttribute: "AddAttribute",
        Name: "Name",
        Value: "Value",
        AttributeName: "Attribute name",
        SearchResult : "Search Result",
        SearchResultArray: "Search results",
        UserProfile : "User Profile",
        Settings : "Settings",
        Logout : "Logout",
        Reset : "Reset",
        Load : "Load",
        Delete : "Delete",
        Count: "Count",
        Query: "Query",
        Table: "Table",
        Result: "Result",
        FileUpload: "FileUpload",
        FlatFileUpload: "Flat file upload",
        ShowQuery: "Show Query",
        FlatFile: "Flat file",
        PrettyTable: "Pretty table",
        RunQuery: "Run query",
        ShowQuery: "Show query",
        EditQuery: "Edit query",
        CancelQuery: "Cancel query",
        DownloadQuery: "Download query",
        DownloadMappedQuery: "Download mapped query",
        RunAllQueries: "Run all queries",
        Active: "Active",
        Activate: "Activate",
        GraphBuilder: "GraphBuilder",
        GraphData: "Graph Data",
        GraphManager: "Data schemes",
        GraphModel: "GraphModel",
        GraphRelation: "GraphRelation",
        Graph: "Graph",
        Graphs: "Graphs",
        Save: "Save",
        GraphModel: "Graph model",
        GraphModels: "Graph models",
        GraphRelation: "Graph relation",
        GraphRelations: "Graph relations",
        FieldsFrom: "FieldsFrom",
        FieldsTo: "FieldsTo",
        Fields: "Fields",
        Drawing: "Drawing",
        Rows: "Rows",
        FillName: "Fill name",
        FillFields: "Fill fields",
        FillGraph: "Fill graph",
        FillDrawing: "Fill drawing",
        LoadCsv: "Load csv file",
        Begin: "Begin",
        End: "End",
        Comparatos: "Comparatos",
        ActiveBin: "ActiveBin",
        InputName: "InputName",
        LoadFromActiveBin: "Load From Active Bin",
    },
    ru: {
        PleaseSignIn: "Вход в систему",
        username: "Логин",
        password: "Пароль",
        dashboard: "Рабочий стол",
        search: "Поиск",
        StartSearch: "Начать поиск",
        CreateSearchQueue: "Сформировать очередь запросов",
        bins: "Корзины запросов",
        ActiveBinData: "Результаты поиска",
        SignIn: "Войти",
        Form: "Форма",
        File: "Файл",
        SearchFormList: "Список форм для поиска",
        SearchForm: "Форма поиска",
        Remove: "Удалить",
        RemoveForm: "Удалить форму",
        AddNewForm: "Добавить новую форму",
        LoadFormsValues: "Загрузить значения из форм",
        AddAttribute: "Добавить атрибут",
        Name: "Имя",
        Value: "Значение",
        AttributeName: "Имя атрибута",
        SearchResult : "Результат поиска",
        SearchResultArray: "Результаты поиска",
        UserProfile : "Профиль",
        Settings : "Настройки",
        Logout : "Выход",
        Reset : "Очистить",
        Load : "Загрузить",
        Delete : "Удалить",
        Count: "Количество",
        Query: "Запрос",
        Table: "Таблица",
        Result: "Результат",
        FileUpload: "Загрузить файл",
        FlatFileUpload: "Загрузить плоский файл",
        ShowQuery: "Показать запрос",
        FlatFile: "Плоский файл",
        PrettyTable: "Таблица (Имя/Значения)",
        RunQuery: "Run query",
        ShowQuery: "Show query",
        EditQuery: "Edit query",
        CancelQuery: "Cancel query",
        DownloadQuery: "Скачать запрос",
        DownloadMappedQuery: "Скачать связанные запросы",
        RunAllQueries: "Запустить все запросы",
        Active: "Активность",
        Activate: "Активировать",
        GraphManager: "Схемы данных",
        GraphBuilder: "Построение графов",
        GraphData: "Данные на схеме",
        GraphModel: "GraphModel",
        GraphRelation: "GraphRelation",
        Graph: "Схема данных",
        Graphs: "Схемы данных",
        Save: "Сохранить",
        GraphModel: "Объект",
        GraphModels: "Объекты",
        GraphRelation: "Связь между объектами",
        GraphRelations: "Связи между объектами",
        FieldsFrom: "Поля начала",
        FieldsTo: "Поля конца",
        Fields: "Поля",
        Drawing: "Стиль отображения",
        Rows: "Кол-во записей",
        FillName: "Укажите название",
        FillFields: "Укажите поля",
        FillGraph: "Выберите граф",
        FillDrawing: "Выберите стиль отображения",
        LoadCsv: "Загрузить csv файл",
        Begin: "Begin",
        End: "End",
        Comparatos: "Comparatos",
        ActiveBin: "Активная корзина",
        InputName: "Введите название",
        LoadFromActiveBin: "Загрузить данные из результата поиска",
    }
});

strings.setLanguage('ru');
