import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
    en:{
        PleaseSignIn: "Please Sign In",
        username: "Username",
        password: "Password",
        dashboard: "Dashboard",
        search: "Search",
        StartSearch: "Start search",
        bins: "Bins",
        SignIn: "Sign In",
        Form: "Form",
        File: "File",
        SearchFormList: "Search Form List",
        SearchForm: "Search Form",
        Remove: "Remove",
        RemoveForm: "Remove form",
        AddNewForm: "Add new form",
        LoadFormsValues: "Load forms values",
        AddAttribute: "AddAttribute",
        Name: "Name",
        Value: "Value",
        AttributeName: "Attribute name",
        SearchResult : "Search Result",
        SearchResultArray: "Search results",
        UserProfile : "User Profile",
        Settings : "Settings",
        Logout : "Logout",
        Reset : "Reset",
        Load : "Load",
        Delete : "Delete",
        Count: "Count",
        Query: "Query",
        Table: "Table",
        Result: "Result",
        FileUpload: "FileUpload",
        FlatFileUpload: "Flat file upload",
        ShowQuery: "Show Query",
        FlatFile: "Flat file",
        PrettyTable: "Pretty table",
        RunQuery: "Run query",
        ShowQuery: "Show query",
        EditQuery: "Edit query",
        CancelQuery: "Cancel query",
        DownloadQuery: "Download query",
        RunAllQueries: "Run all queries",
    },
    ru: {
        PleaseSignIn: "Вход в систему",
        username: "Логин",
        password: "Пароль",
        dashboard: "Рабочий стол",
        search: "Поиск",
        StartSearch: "Начать поиск",
        bins: "Корзины запросов",
        SignIn: "Войти",
        Form: "Форма",
        File: "Файл",
        SearchFormList: "Список форм для поиска",
        SearchForm: "Форма поиска",
        Remove: "Удалить",
        RemoveForm: "Удалить форму",
        AddNewForm: "Добавить новую форму",
        LoadFormsValues: "Загрузить значения из форм",
        AddAttribute: "Добавить атрибут",
        Name: "Имя",
        Value: "Значение",
        AttributeName: "Имя атрибута",
        SearchResult : "Результат поиска",
        SearchResultArray: "Результаты поиска",
        UserProfile : "Профиль",
        Settings : "Настройки",
        Logout : "Выход",
        Reset : "Очистить",
        Load : "Загрузить",
        Delete : "Удалить",
        Count: "Количество",
        Query: "Запрос",
        Table: "Таблица",
        Result: "Результат",
        FileUpload: "Загрузить файл",
        FlatFileUpload: "Загрузить плоский файл",
        ShowQuery: "Показать запрос",
        FlatFile: "Плоский файл",
        PrettyTable: "Таблица (Имя/Значения)",
        RunQuery: "Run query",
        ShowQuery: "Show query",
        EditQuery: "Edit query",
        CancelQuery: "Cancel query",
        DownloadQuery: "Скачать запрос",
        RunAllQueries: "Запустить все запросы",
    }
});

strings.setLanguage('ru');
